// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IMessagingComposer$Type } from "./IMessagingComposer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMessagingComposer"]: IMessagingComposer$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingComposer.sol:IMessagingComposer"]: IMessagingComposer$Type;
  }
}
