// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IOAppCore$Type } from "./IOAppCore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOAppCore"]: IOAppCore$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/interfaces/IOAppCore.sol:IOAppCore"]: IOAppCore$Type;
  }
}
