// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TimelockController$Type } from "./TimelockController";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TimelockController"]: TimelockController$Type;
    ["@openzeppelin/contracts/governance/TimelockController.sol:TimelockController"]: TimelockController$Type;
  }
}
