// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ILayerZeroEndpointV2$Type } from "./ILayerZeroEndpointV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ILayerZeroEndpointV2"]: ILayerZeroEndpointV2$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/ILayerZeroEndpointV2.sol:ILayerZeroEndpointV2"]: ILayerZeroEndpointV2$Type;
  }
}
