// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface PacketDecoder$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "PacketDecoder",
  "sourceName": "@layerzerolabs/lz-evm-oapp-v2/contracts/precrime/libs/Packet.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220188e83864555e35b9e0e31a873d634204a8d47b1db22689bbd97d76589ab75e564736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220188e83864555e35b9e0e31a873d634204a8d47b1db22689bbd97d76589ab75e564736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "PacketDecoder",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PacketDecoder$Type["abi"]>>;
  export function deployContract(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/precrime/libs/Packet.sol:PacketDecoder",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PacketDecoder$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "PacketDecoder",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PacketDecoder$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/precrime/libs/Packet.sol:PacketDecoder",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PacketDecoder$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "PacketDecoder",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PacketDecoder$Type["abi"]>>;
  export function getContractAt(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/precrime/libs/Packet.sol:PacketDecoder",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PacketDecoder$Type["abi"]>>;
}
