// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BaseQMFTechToken$Type } from "./BaseQMFTechToken";
import { NativeQMFTechToken$Type } from "./NativeQMFTechToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BaseQMFTechToken"]: BaseQMFTechToken$Type;
    ["NativeQMFTechToken"]: NativeQMFTechToken$Type;
    ["contracts/QMFTechToken.sol:BaseQMFTechToken"]: BaseQMFTechToken$Type;
    ["contracts/QMFTechToken.sol:NativeQMFTechToken"]: NativeQMFTechToken$Type;
  }
}
