// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OFTCore$Type } from "./OFTCore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OFTCore"]: OFTCore$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oft/OFTCore.sol:OFTCore"]: OFTCore$Type;
  }
}
