// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface MerkleProof$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "MerkleProof",
  "sourceName": "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol",
  "abi": [
    {
      "inputs": [],
      "name": "MerkleProofInvalidMultiproof",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b98e7ab792817e953408e28ea2d5c401d13d4e6da65b05ff5d9f7ffba997851364736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b98e7ab792817e953408e28ea2d5c401d13d4e6da65b05ff5d9f7ffba997851364736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "MerkleProof",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "MerkleProof",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MerkleProof$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MerkleProof$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "MerkleProof",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
}
