// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OFTMsgCodec$Type } from "./OFTMsgCodec";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OFTMsgCodec"]: OFTMsgCodec$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTMsgCodec.sol:OFTMsgCodec"]: OFTMsgCodec$Type;
  }
}
