// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface OFTMsgCodec$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "OFTMsgCodec",
  "sourceName": "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTMsgCodec.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c6002faed9d7298b1245431c8cd2f97ec147c35cec62852b2e7a3b7fe0e2143a64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c6002faed9d7298b1245431c8cd2f97ec147c35cec62852b2e7a3b7fe0e2143a64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "OFTMsgCodec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<OFTMsgCodec$Type["abi"]>>;
  export function deployContract(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTMsgCodec.sol:OFTMsgCodec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<OFTMsgCodec$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "OFTMsgCodec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<OFTMsgCodec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTMsgCodec.sol:OFTMsgCodec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<OFTMsgCodec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "OFTMsgCodec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<OFTMsgCodec$Type["abi"]>>;
  export function getContractAt(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTMsgCodec.sol:OFTMsgCodec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<OFTMsgCodec$Type["abi"]>>;
}
