// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OAppReceiver$Type } from "./OAppReceiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OAppReceiver"]: OAppReceiver$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppReceiver.sol:OAppReceiver"]: OAppReceiver$Type;
  }
}
