// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IOAppPreCrimeSimulator$Type } from "./IOAppPreCrimeSimulator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOAppPreCrimeSimulator"]: IOAppPreCrimeSimulator$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/precrime/interfaces/IOAppPreCrimeSimulator.sol:IOAppPreCrimeSimulator"]: IOAppPreCrimeSimulator$Type;
  }
}
