// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IOFT$Type } from "./IOFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOFT"]: IOFT$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oft/interfaces/IOFT.sol:IOFT"]: IOFT$Type;
  }
}
