// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AirDropQMF$Type } from "./AirDropQMF";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AirDropQMF"]: AirDropQMF$Type;
    ["contracts/AirDropQMF.sol:AirDropQMF"]: AirDropQMF$Type;
  }
}
