// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IOAppReceiver$Type } from "./IOAppReceiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOAppReceiver"]: IOAppReceiver$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/interfaces/IOAppReceiver.sol:IOAppReceiver"]: IOAppReceiver$Type;
  }
}
