// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OAppSender$Type } from "./OAppSender";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OAppSender"]: OAppSender$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol:OAppSender"]: OAppSender$Type;
  }
}
