// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IOAppOptionsType3$Type } from "./IOAppOptionsType3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOAppOptionsType3"]: IOAppOptionsType3$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/interfaces/IOAppOptionsType3.sol:IOAppOptionsType3"]: IOAppOptionsType3$Type;
  }
}
