// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ILayerZeroReceiver$Type } from "./ILayerZeroReceiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ILayerZeroReceiver"]: ILayerZeroReceiver$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/ILayerZeroReceiver.sol:ILayerZeroReceiver"]: ILayerZeroReceiver$Type;
  }
}
