// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OFT$Type } from "./OFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OFT"]: OFT$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oft/OFT.sol:OFT"]: OFT$Type;
  }
}
