// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OApp$Type } from "./OApp";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OApp"]: OApp$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OApp.sol:OApp"]: OApp$Type;
  }
}
