// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IMessagingContext$Type } from "./IMessagingContext";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMessagingContext"]: IMessagingContext$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingContext.sol:IMessagingContext"]: IMessagingContext$Type;
  }
}
