// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IMessagingContext$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IMessagingContext",
  "sourceName": "@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingContext.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getSendContext",
      "outputs": [
        {
          "internalType": "uint32",
          "name": "dstEid",
          "type": "uint32"
        },
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "isSendingMessage",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IMessagingContext",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMessagingContext$Type["abi"]>>;
  export function deployContract(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingContext.sol:IMessagingContext",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMessagingContext$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IMessagingContext",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMessagingContext$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingContext.sol:IMessagingContext",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMessagingContext$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IMessagingContext",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMessagingContext$Type["abi"]>>;
  export function getContractAt(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingContext.sol:IMessagingContext",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMessagingContext$Type["abi"]>>;
}
