// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IMessageLib$Type } from "./IMessageLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMessageLib"]: IMessageLib$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessageLib.sol:IMessageLib"]: IMessageLib$Type;
  }
}
