// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OFTComposeMsgCodec$Type } from "./OFTComposeMsgCodec";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OFTComposeMsgCodec"]: OFTComposeMsgCodec$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTComposeMsgCodec.sol:OFTComposeMsgCodec"]: OFTComposeMsgCodec$Type;
  }
}
