// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface OFTComposeMsgCodec$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "OFTComposeMsgCodec",
  "sourceName": "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTComposeMsgCodec.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122022a01207abe13faeba9b0a872d1adce15047a72c05a4333d7ad7f5ad570854f464736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122022a01207abe13faeba9b0a872d1adce15047a72c05a4333d7ad7f5ad570854f464736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "OFTComposeMsgCodec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<OFTComposeMsgCodec$Type["abi"]>>;
  export function deployContract(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTComposeMsgCodec.sol:OFTComposeMsgCodec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<OFTComposeMsgCodec$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "OFTComposeMsgCodec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<OFTComposeMsgCodec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTComposeMsgCodec.sol:OFTComposeMsgCodec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<OFTComposeMsgCodec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "OFTComposeMsgCodec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<OFTComposeMsgCodec$Type["abi"]>>;
  export function getContractAt(
    contractName: "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTComposeMsgCodec.sol:OFTComposeMsgCodec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<OFTComposeMsgCodec$Type["abi"]>>;
}
