// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IPreCrime$Type } from "./IPreCrime";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPreCrime"]: IPreCrime$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/precrime/interfaces/IPreCrime.sol:IPreCrime"]: IPreCrime$Type;
  }
}
