// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OAppOptionsType3$Type } from "./OAppOptionsType3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OAppOptionsType3"]: OAppOptionsType3$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/libs/OAppOptionsType3.sol:OAppOptionsType3"]: OAppOptionsType3$Type;
  }
}
