// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IOAppMsgInspector$Type } from "./IOAppMsgInspector";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOAppMsgInspector"]: IOAppMsgInspector$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/interfaces/IOAppMsgInspector.sol:IOAppMsgInspector"]: IOAppMsgInspector$Type;
  }
}
