// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OAppCore$Type } from "./OAppCore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OAppCore"]: OAppCore$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppCore.sol:OAppCore"]: OAppCore$Type;
  }
}
