// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface PacketV1Codec$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "PacketV1Codec",
  "sourceName": "@layerzerolabs/lz-evm-protocol-v2/contracts/messagelib/libs/PacketV1Codec.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212205640f164d9ac138d705a5fda7f87f71eaaca0762159b65697046d283a178d92b64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212205640f164d9ac138d705a5fda7f87f71eaaca0762159b65697046d283a178d92b64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "PacketV1Codec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PacketV1Codec$Type["abi"]>>;
  export function deployContract(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/messagelib/libs/PacketV1Codec.sol:PacketV1Codec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PacketV1Codec$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "PacketV1Codec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PacketV1Codec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/messagelib/libs/PacketV1Codec.sol:PacketV1Codec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PacketV1Codec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "PacketV1Codec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PacketV1Codec$Type["abi"]>>;
  export function getContractAt(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/messagelib/libs/PacketV1Codec.sol:PacketV1Codec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PacketV1Codec$Type["abi"]>>;
}
