// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LayerZeroEndpointV2Mock$Type } from "./LayerZeroEndpointV2Mock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LayerZeroEndpointV2Mock"]: LayerZeroEndpointV2Mock$Type;
    ["contracts/mocks/LayerZeroEndpointV2.sol:LayerZeroEndpointV2Mock"]: LayerZeroEndpointV2Mock$Type;
  }
}
