// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface AddressCast$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "AddressCast",
  "sourceName": "@layerzerolabs/lz-evm-protocol-v2/contracts/libs/AddressCast.sol",
  "abi": [
    {
      "inputs": [],
      "name": "AddressCast_InvalidAddress",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "AddressCast_InvalidSizeForAddress",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220472ff67ad3d039842e458e206d2e2c259fc517ca69cdbb437aa61a3c0ee46cab64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220472ff67ad3d039842e458e206d2e2c259fc517ca69cdbb437aa61a3c0ee46cab64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "AddressCast",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<AddressCast$Type["abi"]>>;
  export function deployContract(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/libs/AddressCast.sol:AddressCast",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<AddressCast$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "AddressCast",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<AddressCast$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/libs/AddressCast.sol:AddressCast",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<AddressCast$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "AddressCast",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<AddressCast$Type["abi"]>>;
  export function getContractAt(
    contractName: "@layerzerolabs/lz-evm-protocol-v2/contracts/libs/AddressCast.sol:AddressCast",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<AddressCast$Type["abi"]>>;
}
