// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AddressCast$Type } from "./AddressCast";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AddressCast"]: AddressCast$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/libs/AddressCast.sol:AddressCast"]: AddressCast$Type;
  }
}
